prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d
    resources:
      requests:
        cpu: 500m
        memory: 2Gi

alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: admin
  ingress:
    enabled: true
    hosts: [grafana.hellnet.com.br]