apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - alloy/configmap.yaml
  - alloy/daemonset.yaml
  - alloy/service.yaml
  - grafana/configmap-datasources.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
  - loki/configmap.yaml
  - loki/statefulset.yaml
  - loki/service.yaml
  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml
  - prometheus/configmap.yaml
  - prometheus/serviceaccount.yaml
  - prometheus/clusterrole.yaml
  - prometheus/clusterrolebinding.yaml
  - prometheus/pvc.yaml
  - prometheus/statefulset.yaml
  - prometheus/service.yaml
  - pyroscope/configmap.yaml
  - pyroscope/statefulset.yaml
  - pyroscope/service.yaml
  - tempo/configmap.yaml
  - tempo/statefulset.yaml
   - tempo/service.yaml