---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - namespace.yaml
  - alloy/daemonset.yaml
  - alloy/service.yaml
  - alloy/rbac.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/secret.yaml
  - grafana/pvc.yaml
  - loki/statefulset.yaml
  - loki/service.yaml
  - prometheus/rbac.yaml
  - prometheus/statefulset.yaml
  - prometheus/service.yaml
  - tempo/statefulset.yaml
  - tempo/service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: alloy-config
    files:
      - configs/alloy.alloy
  - name: grafana-datasources
    files:
      - configs/datasources.yaml
  - name: loki-config
    files:
      - configs/loki.yaml
  - name: prometheus-config
    files:
      - configs/prometheus.yml
  - name: tempo-config
    files:
      - configs/tempo.yaml
