apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: prometheus
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: node-exporter
