apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
  - apiGroups: [""]
    resources: [nodes, pods, services, configmaps, secrets, endpoints, persistentvolumeclaims, persistentvolumes, namespaces, replicationcontrollers, limitranges, resourcequotas, events]
    verbs: [list, watch]
  - apiGroups: [apps]
    resources: [daemonsets, deployments, statefulsets, replicasets]
    verbs: [list, watch]
  - apiGroups: [batch]
    resources: [cronjobs, jobs]
    verbs: [list, watch]
  - apiGroups: [autoscaling]
    resources: [horizontalpodautoscalers]
    verbs: [list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [list, watch]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses, volumeattachments]
    verbs: [list, watch]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [list, watch]
