---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-actions-runner-webhook
  namespace: arc-actions
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "secrets", "serviceaccounts"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-actions-runner-webhook
  namespace: arc-actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-actions-runner-webhook
subjects:
  - kind: ServiceAccount
    name: arc-actions-runner-webhook
    namespace: arc-actions
