---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-actions
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guilhermelinosp/monitoring
    targetRevision: main
    path: arc-actions
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-actions
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
