---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-arc-runner-autoscaler
  namespace: arc-actions
spec:
  scaleTargetRef:
    name: runner-arc-runner
    kind: RunnerDeployment
  minReplicas: 1
  maxReplicas: 5
  scaleUpTriggers:
    - duration: 5m
