---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-org-autoscaler
  namespace: arc-actions
spec:
  scaleTargetRef:
    name: runner-org
    kind: RunnerDeployment
  minReplicas: 0
  maxReplicas: 5
  scaleUpTriggers:
    - duration: 5m
