---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-actions

resources:
  - namespace.yaml
  - arc-actions-runner-webhook-sa.yaml
  - arc-actions-runner-webhook-rbac.yaml
  - arc-actions-runner-webhook-deployment.yaml
  - arc-actions-runner-webhook-svc.yaml
  - runner-deploy-arc-runner.yaml
  - runner-deploy-monitoring.yaml
  - hra-arc-runner.yaml
  - hra-arc-infra.yaml
  - hra-org.yaml
  - httproute-webhook.yaml
