apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-config
  namespace: monitoring
data:
  pyroscope.yaml: |
    storage:
      backend: filesystem
      filesystem:
        directory: /var/pyroscope
